language: java
jdk: oraclejdk8
script: ./gradlew assemble test
sudo: required

before_install:
     - chmod +x gradlew

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "6e0f357789f538324bbf41fbacab7f30797a23ab"
  file_glob: true
  file: SmartTomcat*.zip
  on:
    tags: true
    all_branches: true
